# Custom Language File for Launcher Customizer

[ejs.app]
#title = "Helios Launcher"
title = "WetCat Launcher (Beta)"

[ejs.landing]
mediaGitHubURL = "https://github.com/raykoshima/WetCat-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/raykoshima/WetCat-Launcher"
supportLink = "https://github.com/raykoshima/WetCat-Launcher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO WETCAT LAUNCHER"
welcomeDescription = ""
welcomeDescCTA = "You are just a few clicks away from WetCat."
